#pragma once

#define MODCHIP_CMD_PREFIX 0xcf
#define MODCHIP_CMD_GROUP0 0x0c

#define MODCHIP_CMD_DISABLE_NEXT_OSDSYS_HOOK ((0x1c61 << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_GET_EE_STAGE1_SIZE       ((0xd008 << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_GET_EE_STAGE2_SIZE       ((0xc46e << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_GET_EE_STAGE2            ((0x882c << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_READ_APP                 ((0x0a6c << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_KV_GET                   ((0x1d27 << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_KV_SET                   ((0x40b1 << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)
#define MODCHIP_CMD_GIT_REV                  ((0x1e6a << 16) | (MODCHIP_CMD_GROUP0 << 8) | MODCHIP_CMD_PREFIX)

enum
{
    MODCHIP_SETTINGS_MENU_AUTOBOOT = 0,
    MODCHIP_SETTINGS_MENU_AUTOBOOT_DELAY = 1,
    MODCHIP_SETTINGS_MENU_AUTOBOOT_ITEM_IDX = 2,
    MODCHIP_SETTINGS_MENU_OSDSYS_SETTINGS = 3,
    MODCHIP_SETTINGS_KEYS_TOTAL,
};
